workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.zard.flashcard"
        APP_ID: 69587605cd4ec8cbc103fc68
      node: 22
      xcode: latest
      # NÃO usar cocoapods - projeto usa SPM
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild archive \
            -project "App.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          echo "=== Export IPA ==="
          echo "CM_BUILD_DIR: $CM_BUILD_DIR"
          
          # Criar diretório de destino
          mkdir -p "$CM_BUILD_DIR/build/ipa"
          
          # CRIAR export_options.plist DIRETAMENTE no local onde será usado
          cat > "$CM_BUILD_DIR/export_options.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>development</string>
    <key>teamID</key>
    <string></string>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>stripSwiftSymbols</key>
    <true/>
</dict>
</plist>
EOF
          
          echo "Arquivo export_options.plist criado em: $CM_BUILD_DIR/export_options.plist"
          ls -la "$CM_BUILD_DIR/export_options.plist"
          cat "$CM_BUILD_DIR/export_options.plist"
          
          # Verificar se o archive existe
          if [ ! -d "$CM_BUILD_DIR/build/App.xcarchive" ]; then
            echo "ERRO: Archive não encontrado!"
            ls -la "$CM_BUILD_DIR/build/" || true
            exit 1
          fi
          
          # Exportar IPA usando caminho absoluto
          EXPORT_PLIST="$CM_BUILD_DIR/export_options.plist"
          echo "Exportando IPA com arquivo: $EXPORT_PLIST"
          
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/build/ipa" \
            -exportOptionsPlist "$EXPORT_PLIST"
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - gabrielrenatosouzadearaujo@gmail.com
        notify:
          success: true
          failure: false
