workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.zard.flashcard"
        APP_ID: 69587605cd4ec8cbc103fc68
      node: 22
      xcode: latest
      # NÃO usar cocoapods - projeto usa SPM
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild archive \
            -project "App.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          # Verificar e copiar export_options.plist
          echo "Verificando arquivo export_options.plist..."
          ls -la ios/App/*.plist || echo "Arquivos plist não encontrados em ios/App/"
          pwd
          
          # Copiar export_options.plist para local acessível
          if [ -f "ios/App/export_options.plist" ]; then
            cp ios/App/export_options.plist $CM_BUILD_DIR/export_options.plist
            echo "Arquivo copiado para $CM_BUILD_DIR/export_options.plist"
          else
            echo "ERRO: export_options.plist não encontrado!"
            exit 1
          fi
          
          # Verificar se o arquivo foi copiado
          if [ ! -f "$CM_BUILD_DIR/export_options.plist" ]; then
            echo "ERRO: Falha ao copiar export_options.plist!"
            exit 1
          fi
          
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ipa \
            -exportOptionsPlist $CM_BUILD_DIR/export_options.plist
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - gabrielrenatosouzadearaujo@gmail.com
        notify:
          success: true
          failure: false
