workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "frontend/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.zard.flashcard"
        APP_ID: 69587605cd4ec8cbc103fc68
      node: 22
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm ci
      - name: Build web assets
        script: |
          cd frontend
          npm run build
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios/App
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcodebuild build-for-testing \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            | xcpretty
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/export_options.plist \
            -exportPath $CM_BUILD_DIR/build/ipa \
            | xcpretty
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - gabrielrenatosouzadearaujo@gmail.com
        notify:
          success: true
          failure: false

